name: update goodreads

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    name: Update README with Goodreads
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (fetch full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Goodreads action for Read Books
        uses: zwacky/goodreads-profile-workflow@v1.2.4
        with:
          goodreads_user_id: "178629903"
          shelf: "read"
          max_books_count: 5
          comment_tag_name: "GOODREADS-LIST"

      - name: Run Goodreads action for Currently Reading Books
        uses: zwacky/goodreads-profile-workflow@v1.2.4
        with:
          goodreads_user_id: "178629903"
          shelf: "currently-reading"
          max_books_count: 5
          comment_tag_name: "CURRENTLY-READING-LIST"
          template: "**📖 [$title]($url) by $author**" # Updated template line

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes if any
        id: commit
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          git add -A
          git commit -m "Synced and updated with user's goodreads book lists [skip ci]"
          echo "no_changes=false" >> $GITHUB_OUTPUT

      - name: Pull Rebase and Push changes
        if: steps.commit.outputs.no_changes == 'false'
        id: push_changes
        run: |
          git pull --rebase origin main
          git push origin main
        continue-on-error: true

      - name: Create Pull Request on Push Failure
        if: steps.commit.outputs.no_changes == 'false' && steps.push_changes.outcome == 'failure'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Synced and updated with user's goodreads book lists"
          title: "Goodreads sync: update README"
          body: |
            The automated Goodreads sync tried to push changes but failed.
            This might be due to branch protection rules or other conflicts.
            This PR contains the changes from the scheduled sync so you can review and merge.
          base: main
          branch: gh-actions/goodreads-sync-${{ github.run_id }}